appname/__init__.py
#! ../env/bin/python

from flask import Flask, render_template, request, g
from webassets.loaders import PythonLoader as PythonAssetsLoader

from appname import assets
from appname import constants
from appname.models import db
from appname.api.resources import api_blueprint
from appname.api import handle_api_error
from appname.controllers.main import main
from appname.controllers.auth import auth
from appname.controllers.oauth import google_blueprint
from appname.controllers.store import store
from appname.controllers.settings import settings_blueprint
from appname.controllers.admin.jobs import jobs
from appname.controllers.webhooks.stripe import stripe_blueprint
from appname.controllers.dashboard import dashboard_blueprints

from appname import utils
from appname.helpers import view as view_helpers
from appname.converter import custom_converters
from appname.extensions import (
    admin,
    assets_env,
    cache,
    csrf,
    debug_toolbar,
    hashids,
    login_manager,
    limiter,
    mail,
    rq2,
    sentry,
    storage,
    stripe,
    token
)
from appname.forms import SimpleForm


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. appname.settings.ProdConfig
    """

    app = Flask(__name__)
    app.config.from_object(object_name)

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # initalize Flask Login
    login_manager.init_app(app)

    # initialize Flask-RQ2 (job queue)
    rq2.init_app(app)

    # CSRF Protection
    csrf.init_app(app)

    # File Storage
    storage.init_app(app)

    # Special URL converters
    custom_converters.init_app(app)

    token.init_app(app)
    mail.init_app(app)
    limiter.init_app(app)
    stripe.init_app(app)
    hashids.init_app(app)

    if app.config.get('SENTRY_DSN') and not app.debug:
        sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        @app.errorhandler(500)
        def internal_server_error(error):
            return render_template('errors/500.html',
                                   event_id=g.sentry_event_id,
                                   public_dsn=sentry.client.get_public_dsn(
                                       'https')
                                   ), 500

    @app.errorhandler(404)
    def not_found_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('errors/404.html'), 404

    @app.errorhandler(401)
    def permission_denied_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('tabler/401.html'), 401

    @app.before_request
    def check_for_confirmation(*args, **kwargs):
        pass
        # TODO: Check later.
        # if REQUIRE_EMAIL_CONFIRMATION:
        #     # If we have a logged in user, we can check if they have confirmed their email or not.
        #     if not current_user.is_authenticated or current_user.email_confirmed:
        #         return
        #     resend_confirm_link = url_for('auth.resend_confirmation')
        #     text = Markup(
        #         'Please confirm your email. '
        #         '<a href="{}" class="alert-link">Click here to resend</a>'.format(resend_confirm_link))
        #     flash(text, 'warning')

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # Set some globals for Jinja templating
    app.jinja_env.globals.update({
        'utils': utils,
        'view_helpers': view_helpers,
        'debug': app.debug,
        'constants': constants,
        'simple_form': SimpleForm,
        'features': {
            'oauth':  app.config["GOOGLE_OAUTH_CLIENT_ID"] != 'bad_key',
            'segment':  app.config["SEGMENT_ANALYTICS_KEY"],
        },
    })

    # register our blueprints
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(google_blueprint, url_prefix='/oauth')
    app.register_blueprint(store)
    app.register_blueprint(settings_blueprint)

    # Register user dashboard blueprints
    for blueprint in dashboard_blueprints:
        app.register_blueprint(blueprint, url_prefix='/dashboard')

    # API
    app.register_blueprint(api_blueprint, url_prefix='/api')
    csrf.exempt(api_blueprint)

    app.register_blueprint(stripe_blueprint, url_prefix='/webhooks')
    csrf.exempt(stripe_blueprint)

    # Admin Tools
    app.register_blueprint(jobs, url_prefix='/admin/rq')
    admin.init_app(app)

    # If you use websockets/realtime features
    # socketio.init_app(app)

    return app

appname/api/__init__.py
from flask import Blueprint, request, jsonify

from flask_restful.representations.json import output_json
from flask_restful import reqparse, fields, abort
import flask_restful as restful

from appname.extensions import login_manager
from appname.models.user import User

api_blueprint = Blueprint('api', __name__)
api_blueprint.config = {}

api = restful.Api(api_blueprint)

API_VERSION = 'v1'
API_BASE = '/'  # API_BLUEPRINT prefix is 'api'

@api.representation('application/json')
def envelope_api(data, code, headers=None):
    """ API response envelope (for metadata/pagination).
    Optionally wraps JSON response in envelope.
    This is for successful requests only.

        data is the object returned by the API.
        code is the HTTP status code as an int
    """
    if not request.args.get('envelope'):
        return output_json(data, code, headers)
    message = 'success'
    if 'message' in data:
        message = data['message']
        del data['message']
    data = {
        'data': data,
        'code': code,
        'message': message
    }
    return output_json(data, code, headers)

@login_manager.request_loader
def load_user_from_request(request):
    # Only functional for API Endpoints
    if not request.endpoint or not request.endpoint.startswith("api."):
        return None

    # first, try to login using the api_key url arg
    api_key = request.args.get('api_key')
    if not api_key:
        return None
    user_id, _ = api_key.split('-')
    user = User.get_by_hashid(user_id)
    if user and user.check_api_key_hash(api_key):
        return user

def custom_abort(status_code, message, data=None):
    response = jsonify({
        'code': status_code,
        'data': data,
        'message': message,
    })
    response.status_code = status_code
    return response

def handle_api_error(err):
    return custom_abort(404, str(err))

class Resource(restful.Resource):
    method_decorators = []
    required_scopes = {}
    # applies to all inherited resources

    def __repr__(self):
        return "<Resource {0}>".format(self.__class__.__name__)

    def make_response(self, data, *args, **kwargs):
        return super().make_response(data, *args, **kwargs)


class BaseAPISchema():
    """ APISchema describes the input and output formats for
    resources. The parser deals with arguments to the API.
    The API responses are marshalled to json through get_fields
    """
    get_fields = {}

    def __init__(self):
        self.parser = reqparse.RequestParser()

    def parse_args(self):
        return self.parser.parse_args()

appname/controllers/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session, abort
from flask_login import login_user, logout_user, login_required, current_user

import appname.constants as constants

from appname.forms import SimpleForm
from appname.forms.login import LoginForm, SignupForm, RequestPasswordResetForm, ChangePasswordForm
from appname.models import db
from appname.models.user import User
from appname.models.teams import TeamMember
from appname.mailers.auth import ConfirmEmail, ResetPassword
from appname.extensions import login_manager, token, limiter

auth = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    login_hint = request.args.get('login_hint')
    return redirect(url_for('auth.login', login_hint=login_hint))

@auth.route("/login", methods=["GET", "POST"])
@limiter.limit("20/minute")
def login():
    if not constants.ALLOW_PASSWORD_LOGIN:
        return render_template("auth/oauth_only_login.html")

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for("main.home"))

    return render_template("auth/login.html", form=form)

@auth.route("/signup", methods=["GET", "POST"])
@limiter.limit("10/minute")
def signup():
    if not constants.ALLOW_SIGNUPS:
        return abort(404)

    form = SignupForm(invite_secret=request.args.get('invite_secret'))

    if form.validate_on_submit():
        team_secret = form.invite_secret.data
        invite = (TeamMember.query.filter_by(invite_secret=team_secret, activated=False)
                            .one_or_none())

        if invite:
            user = User(form.email.data, form.password.data,
                        email_confirmed=True, team=invite.team)
            invite.user = user
            db.session.add(invite)
        else:
            user = User(form.email.data, form.password.data)
        db.session.add(user)
        db.session.commit()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        if constants.REQUIRE_EMAIL_CONFIRMATION:
            # Send confirm email
            ConfirmEmail(user).send()

        flash("Welcome to appname.", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/signup.html", form=form, invite_secret=request.args.get('invite_secret'))

@auth.route("/auth/logout")
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("main.home"))

@auth.route("/confirm/<string:code>")
def confirm(code):
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)

    try:
        email = token.decode(code, salt=constants.EMAIL_CONFIRMATION_SALT)
    except Exception:
        email = None

    if not email:
        # TODO: Render a nice error page here.
        return abort(404)

    user = User.query.filter_by(email=email).first()
    if not user:
        return abort(404)
    user.email_confirmed = True
    db.session.commit()

    if current_user == user:
        flash('Succesfully confirmed your email', 'success')
        return redirect(url_for("dashboard_home.index"))
    else:
        flash('Confirmed your email. Please login to continue', 'success')
        return redirect(url_for("auth.login"))


@auth.route("/auth/resend-confirmation", methods=["GET", "POST"])
@limiter.limit("5/minute")
@login_required
def resend_confirmation():
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)
    if current_user.email_confirmed:
        return redirect(url_for("dashboard_home.index"))

    form = SimpleForm()
    if form.validate_on_submit():
        if ConfirmEmail(current_user).send():
            flash(
                "Sent confirmation to {}".format(
                    current_user.email),
                'success')
        return redirect(url_for("dashboard_home.index"))

    return render_template('auth/resend_confirmation.html', form=form)

@auth.route("/auth/reset_password", methods=["GET", "POST"])
@limiter.limit("20/hour")
def request_password_reset():
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))
    form = RequestPasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        if user:
            ResetPassword(user).send()
            flash("We sent you a password reset email.", "success")
            return redirect(url_for('auth.login'))
        else:
            flash("Hmm. That email doesn't appear to be registered ", "success")
    return render_template("auth/request_password_reset.html", form=form)

@auth.route("/auth/reset_password/<string:code>", methods=["GET", "POST"])
@limiter.limit("20/hour")
def reset_password(code):
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))

    try:
        email = token.decode(code, salt=constants.PASSWORD_RESET_SALT)
    except Exception:
        email = None

    if not email:
        return abort(403)

    form = ChangePasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=email).one()
        user.password = form.password.data
        db.session.commit()
        login_user(user)

        flash("Changed your password succesfully", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/reset_password.html", form=form)


@auth.route("/reauth", methods=["GET", "POST"])
def reauth():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        login_user(user)

        flash("Re-authenticated successfully.", "success")
        return redirect(request.args.get("next", url_for("user_settings.index")))
    return render_template("reauth.html", form=form)

@auth.route('/invite/<hashid:invite_id>/join')
@login_required
def join_team(invite_id):
    invite = TeamMember.query.get(invite_id)
    if not invite or invite.user != current_user:
        return abort(404)

    invite.activate(current_user.id)
    return redirect(url_for("dashboard_home.index"))

@auth.route('/join/<hashid:invite_id>/<string:secret>')
@limiter.limit("20/minute")
def invite_page(invite_id, secret):
    invite = TeamMember.query.get(invite_id)
    if not invite.invite_secret or invite.invite_secret != secret or invite.activated:
        return abort(404)

    if current_user.is_authenticated and invite.user == current_user:
        return redirect(url_for(".join_team", invite_id=invite.id))

    form = SignupForm(invite_secret=invite.invite_secret)
    return render_template("auth/invite.html", form=form, invite=invite)

appname/controllers/dashboard/__init__.py
from .home import blueprint as home_blueprint
from .team import blueprint as team_blueprint
from .files import blueprint as files_blueprint

dashboard_blueprints = [
    home_blueprint,
    team_blueprint,
    files_blueprint
]

appname/controllers/main.py
import stripe

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

from appname.extensions import cache

main = Blueprint('main', __name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_home.index'))
    return render_template('lander/index.html', stripe_publishable_key=stripe.publishable_key)

@main.route('/beta')
@cache.cached(timeout=1000, unless=lambda: current_user.is_authenticated)
def beta():
    return "Coming Soon", 200

appname/controllers/oauth/__init__.py
from .google import blueprint as google_blueprint

appname/controllers/realtime.py
from flask_login import current_user

from flask_socketio import join_room, leave_room, send
from appname.extensions import socketio

@socketio.on('connect')
def connect():
    if not current_user.is_authenticated:
        pass
    return

@socketio.on('disconnect')
def disconnect():
    if not current_user.is_authenticated:
        pass
    return

@socketio.on('join')
def on_join(data):
    username = data['username']
    room = data['room']
    join_room(room)
    send(username + ' has entered the room.', room=room)

@socketio.on('leave')
def on_leave(data):
    username = data['username']
    room = data['room']
    leave_room(room)
    send(username + ' has left the room.', room=room)

appname/controllers/store.py
import stripe

from flask import Blueprint, flash, render_template, request

from appname.models.user import User
from appname.extensions import csrf

from appname.mailers.store import PurchaseReceipt

store = Blueprint('store', __name__)

@store.route('/store')
def home():
    return render_template('store/product.html', stripe_publishable_key=stripe.publishable_key)


@store.route('/store/payment', methods=['POST'])
@csrf.exempt
def payment():

    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken']
    )

    stripe.Charge.create(
        customer=customer.id,
        amount=4999,
        currency='usd',
        description='Ingite Flask App Code'
    )

    user = User.lookup_or_create_by_email(request.form['stripeEmail'])
    PurchaseReceipt(user).send()

    flash("Payment processed. You'll get an email shortly", 'success')

    return render_template('store/product.html')

appname/helpers/__init__.py
# Helpers encompass logic that doesn't belong in controllers or
# in views. They are application specific and usually cannot be
# directly reused.

appname/models/teams/__init__.py
# To get Flask Migrate to pick these up, import this module in appname/manage.py
from .team_member import TeamMember  # noqa
from .team import Team  # noqa

appname/templates/lander/index.html
{% extends "lander/base.html" %}

{% block title %}Ignite{% endblock %}

{% block js %}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}


{% block body %}
{% set bg_color_class = ['', 'bg-blue', 'bg-dark-purple', 'bg-grey', 'bg-dark-blue']|random %}
<section class="hero">
	<div class="hero-bg {{bg_color_class}}"></div>
	<header class="header">
		<div class="container nav-header">
			<a href="https://github.com/sumukh/ignite" target="_blank" class="logo">
				<img src="{{ url_for('static', filename='public/ignite/ignite-icon.svg') }}" class="logo-icon h-6" alt="Ignite">
				ignite
			</a>
			<div class="links">
				<a href="#pricing">Pricing</a>
				<a href="{{ url_for('auth.signup') }}">Demo</a>
			</div>
		</div>
	</header>


	<div class="container">
		<div class="row hero-content">
			<div class="col-sm">
				<div class="hero-header">
					<h1 class="hero-title">Batteries Included</h1>
					<p class="hero-description">Ignite is a starting point for Flask web applications that handles the
					basics of SaaS products (like user login and subscription billing) for you.
					</p>

					<div class="hero-cta">
						<a href="{{ url_for('auth.signup') }}" class="btn btn-outline-light btn-outline hero-cta-btn">Demo</a>
						<a href="#pricing" class="btn btn-light hero-cta-btn">Download</a>
					</div>
				</div>
			</div>
			<div class="col-sm hero-img-column">
				<div class="hero-browser image-animate-container">
					<img class="hero-screenshot image-animate-img" src="{{ url_for('static', filename='public/ignite/demo-1.png') }}" x="0" y="0" height="400" />
				</div>
			</div>
		</div>
	</div>
</section>

<section class="section features">
	<div class="container">
		<h2 class="section-title">Get a headstart on your web app</h2>
		<div class="section-description mb-6">
			<div class="row">
				<div class="col-md-4 col-xs-12 feature-block">
					<i class="fa fa-code feature-icon"></i>
					<div class="feature-text-block">
						<div class="feature-heading">Based on Flask & Python 3</div>
						<div class="features-text-block">
							Ignite builds upon Flask, a popular framework for Python used by many web applications (including Pinterest).
						</div>
					</div>
				</div>
				<div class="col-md-4 col-xs-12 feature-block">
						<i class="fa fa-cc-stripe feature-icon"></i>
						<div class="feature-text-block">
							<div class="feature-heading">Subscription & One Off Billing</div>
							<div class="features-text-block">
								Accept credit card payments and issue receipts through Stripe. Ignite Pro supports recurring billing.
							</div>
						</div>
				</div>
				<div class="col-md-4 col-xs-12 feature-block">
						<i class="fa fa-users feature-icon"></i>
						<div class="feature-text-block">
							<div class="feature-heading">Users & Teams</div>
							<div class="features-text-block">
								Ignite handles account registration, login, OAuth login (like login with Google), password resets, teams, and email confirmation.
							</div>
						</div>
				</div>

			</div>
			<div class="row">

				<div class="col-md-4 col-xs-12 feature-block">
					<i class="fa fa-building feature-icon"></i>
					<div class="feature-text-block">
						<div class="feature-heading">GDPR Features</div>
						<div class="features-text-block">
							User Data Export & PII Data Deletion framework is built in along with a variety of resources for GDPR.
						</div>
					</div>
				</div>

				<div class="col-md-4 col-xs-12 feature-block">
					<i class="fa fa-html5 feature-icon"></i>
					<div class="feature-text-block">
						<div class="feature-heading">Bootstrap 4 & HTML 5</div>
						<div class="features-text-block">
							Ignite uses Bootstrap, the most popular frontend HTML & CSS framework. The prebuilt UIs
							serves as a good starting point for your app.
						</div>
					</div>
				</div>
				<div class="col-md-4 feature-block">
					<i class="fa fa-cloud feature-icon"></i>
					<div class="feature-text-block">
						<div class="feature-heading">Scalable</div>
						<div class="features-text-block">
							Ignite supports deployment on cloud providers and builds upon modern best practices for Flask applications.
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
				<div class="col-sm">
				   <ul class="list-unstyled icon-offset">
					  <li><strong>User Authentication</strong></li>
					  <li><a href="#">User Login</a></li>
					  <li><a href="#">Login with Google/OAuth</a></li>
					  <li><a href="#">Email Confirmation</a></li>
					  <li><a href="#">Forgot/Change Password</a></li>
					  <li><a href="#">Teams Invitations</a></li>
					  <li><a href="#">Teams Permission Levels</a></li>
					  <li><a href="#">Email Notifications</a></li>
					  <li><a href="#">User API Tokens</a></li>
					  <li><a href="#">Data Export</a> <a href="#pricing" class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="Available in Ignite PRO Version"> PRO</a></li>
					  <li><a href="#">Data Deletion</a> <a href="#pricing" class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="Available in Ignite PRO Version"> PRO</a></li>
				   </ul>
				</div>
				<div class="col-sm">
					<ul class="list-unstyled icon-offset">
						<li><strong>Server</strong></li>
						<li><a href="#">User Facing API</a></li>
						<li><a href="#">Caching</a></li>
						<li><a href="#">Rate Limiting</a></li>
						<li><a href="#">Error Tracking</a></li>
						<li><a href="#">Admin Dashboard</a></li>
						<li><a href="#">File Uploads <small>(S3, Google Cloud, etc)</small> </a></li>
						<li><a href="#">Job Queue</a></li>
						<li><a href="#">Realtime Socket.io</a></li>
						<li><a href="#">Web Analytics</a></li>
						<li><a href="#">Stripe Webhooks</a> <a href="#pricing" class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="Available in Ignite PRO Version">PRO</a></li>
					</ul>
				   <ul class="list-unstyled icon-offset">
					  <li><strong>Developer Tools</strong></li>
					  <li><a href="#">Basic Test Suite</a></li>
					  <li><a href="#">Continous Integration Setup</a></li>
					  <li><a href="#">Local Development Utilities</a></li>
					  <li><a href="#">Editor Integration (VSCode - Run/Debug)</a></li>
				   </ul>
				</div>
				<div class="col-sm">
				   <ul class="list-unstyled icon-offset">
					  <li><strong>Design</strong></li>
					  <li><a href="#">Admin Dashboard UI </a></li>
					  <li><a href="#"> UI Sketch Templates </a></li>
					  <li><a href="#">Charts</a></li>
					  <li><a href="#">Email Templates</a></li>
					  <li><a href="#">Login & Error Page</a></li>
					  <li><a href="#">Font Icons</a></li>
					  <li><a href="#">Asset Bundling System</a></li>
					  <li><a href="#">Landing Page Design</a> <a href="#pricing" class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="Available in Ignite PRO Version"> PRO</a></li>
					  <li><a href="#">Video Guides</a> <a href="#pricing" class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="Available in Ignite PRO Version">PRO</a></li>
				   </ul>
				   <ul class="list-unstyled icon-offset">
						<li><strong>Infrastructure</strong></li>
						<li><a href="#">Database Migrations</a></li>
						<li><a href="#">Heroku/Dokku Deployment</a></li>
						<li><a href="#">AWS/Google Cloud Deployment</a></li>
						<li><a href="#">Docker Container Support</a></li>
					</ul>
				</div>

		</div>
	</div>
</section>

<section class="section pricing py-5" id="pricing">
	<div class="pricing-bg {{bg_color_class}}"> </div>
	<div class="container pricing-body">
		<h2 class="section-title">Pricing</h2>
		<div class="container">
				<div class="row">
						<!-- Free Tier -->
						<div class="col-lg-4">
						  <div class="card mb-5 mb-lg-0">
							<div class="card-body">
							  <h5 class="card-title text-muted text-uppercase text-center">Non Commerical</h5>
							  <h6 class="card-price text-center">Free<span class="period"></span></h6>
							  <hr>
							  <ul class="fa-ul">
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>User Authentication</li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>Source Code Available</li>
								<li class="text-muted">
									<span class="fa-li"><i class="fa red-check fa-times"></i></span>
									<strong>No Commerical Usage</strong>
								</li>
								<li class="text-muted"><span class="fa-li"><i class="fa red-check fa-times"></i></span>Must include Ignite link/credit</li>
							  </ul>
							  <hr>

							  <a href="https://github.com/sumukh/ignite" target="_blank" class="btn btn-block btn-outline-dark text-uppercase">View Source Code</a>
							</div>
						  </div>
						</div>
						<!-- Plus Tier -->
						<div class="col-lg-4">
						  <div class="card card-highlighted mb-5 mb-lg-0">
							<div class="card-body">
							  <h5 class="card-title text-muted text-uppercase text-center">PRO</h5>
							  <h6 class="card-price text-center">$199<span class="period">/site</span></h6>
							  <hr>
							  <ul class="fa-ul">
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span><strong>Commercial Usage</strong></li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>Stripe Checkout</li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>
									OAuth Login
								</li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>GDPR Features</li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>Video Guides</li>
							  </ul>
							  <hr>

							  <a href="https://gum.co/xFvLo?wanted=true" class="btn btn-block btn-primary text-uppercase">Purchase</a>
							</form>
							</div>
						  </div>
						</div>
						<!-- Pro Tier -->
						<div class="col-lg-4">
						  <div class="card">
							<div class="card-body">
							  <h5 class="card-title text-muted text-uppercase text-center">Site License</h5>
							  <h6 class="card-price text-center">$1999</h6>
							  <hr>
							  <ul class="fa-ul">
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span><strong>Commercial License</strong></li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>Everything in Ignite Pro </li>
								<li><span class="fa-li"><i class="fa green-check fa-check"></i></span>Use for multiple applications</li>

							  </ul>
							  <hr>

							  <a href="mailto:{{ constants.SUPPORT_EMAIL }}" class="btn btn-block btn-secondary text-uppercase">Contact Us</a>
							</div>
						  </div>
						</div>
				</div>

		</div>
	</div>
</section>


<footer class="footer">
	<div class="container">
		<div class="row align-items-center text-center">
			<div class="col-md-auto">
				<a href="https://github.com/sumukh/ignite">License & Credits</a>
				・
				<a href="https://github.com/sumukh/ignite">Privacy</a>
			</div>
			<div class="col-md-auto mt-2 mt-sm-0 ml-sm-auto">
				Powered by <a href="https://github.com/sumukh/ignite">Ignite</a> for Flask
				<!-- You must purchase a license of Ignite to remove the above disclaimer -->
			</div>
		</div>
	</div>
</footer>

{% endblock %}