appname/__init__.py
#! ../env/bin/python

from flask import Flask, render_template, request, g
from webassets.loaders import PythonLoader as PythonAssetsLoader

from appname import assets
from appname import constants
from appname.models import db
from appname.api.resources import api_blueprint
from appname.api import handle_api_error
from appname.controllers.main import main
from appname.controllers.auth import auth
from appname.controllers.oauth import google_blueprint
from appname.controllers.store import store
from appname.controllers.settings import settings_blueprint
from appname.controllers.admin.jobs import jobs
from appname.controllers.webhooks.stripe import stripe_blueprint
from appname.controllers.dashboard import dashboard_blueprints

from appname import utils
from appname.helpers import view as view_helpers
from appname.converter import custom_converters
from appname.extensions import (
    admin,
    assets_env,
    cache,
    csrf,
    debug_toolbar,
    hashids,
    login_manager,
    limiter,
    mail,
    rq2,
    sentry,
    storage,
    stripe,
    token
)
from appname.forms import SimpleForm


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. appname.settings.ProdConfig
    """

    app = Flask(__name__)
    app.config.from_object(object_name)

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # initalize Flask Login
    login_manager.init_app(app)

    # initialize Flask-RQ2 (job queue)
    rq2.init_app(app)

    # CSRF Protection
    csrf.init_app(app)

    # File Storage
    storage.init_app(app)

    # Special URL converters
    custom_converters.init_app(app)

    token.init_app(app)
    mail.init_app(app)
    limiter.init_app(app)
    stripe.init_app(app)
    hashids.init_app(app)

    if app.config.get('SENTRY_DSN') and not app.debug:
        sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        @app.errorhandler(500)
        def internal_server_error(error):
            return render_template('errors/500.html',
                                   event_id=g.sentry_event_id,
                                   public_dsn=sentry.client.get_public_dsn(
                                       'https')
                                   ), 500

    @app.errorhandler(404)
    def not_found_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('errors/404.html'), 404

    @app.errorhandler(401)
    def permission_denied_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('tabler/401.html'), 401

    @app.before_request
    def check_for_confirmation(*args, **kwargs):
        pass
        # TODO: Check later.
        # if REQUIRE_EMAIL_CONFIRMATION:
        #     # If we have a logged in user, we can check if they have confirmed their email or not.
        #     if not current_user.is_authenticated or current_user.email_confirmed:
        #         return
        #     resend_confirm_link = url_for('auth.resend_confirmation')
        #     text = Markup(
        #         'Please confirm your email. '
        #         '<a href="{}" class="alert-link">Click here to resend</a>'.format(resend_confirm_link))
        #     flash(text, 'warning')

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # Set some globals for Jinja templating
    app.jinja_env.globals.update({
        'utils': utils,
        'view_helpers': view_helpers,
        'debug': app.debug,
        'constants': constants,
        'simple_form': SimpleForm,
        'features': {
            'oauth':  app.config["GOOGLE_OAUTH_CLIENT_ID"] != 'bad_key',
            'segment':  app.config["SEGMENT_ANALYTICS_KEY"],
        },
    })

    # register our blueprints
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(google_blueprint, url_prefix='/oauth')
    app.register_blueprint(store)
    app.register_blueprint(settings_blueprint)

    # Register user dashboard blueprints
    for blueprint in dashboard_blueprints:
        app.register_blueprint(blueprint, url_prefix='/dashboard')

    # API
    app.register_blueprint(api_blueprint, url_prefix='/api')
    csrf.exempt(api_blueprint)

    app.register_blueprint(stripe_blueprint, url_prefix='/webhooks')
    csrf.exempt(stripe_blueprint)

    # Admin Tools
    app.register_blueprint(jobs, url_prefix='/admin/rq')
    admin.init_app(app)

    # If you use websockets/realtime features
    # socketio.init_app(app)

    return app

appname/api/__init__.py
from flask import Blueprint, request, jsonify

from flask_restful.representations.json import output_json
from flask_restful import reqparse, fields, abort
import flask_restful as restful

from appname.extensions import login_manager
from appname.models.user import User

api_blueprint = Blueprint('api', __name__)
api_blueprint.config = {}

api = restful.Api(api_blueprint)

API_VERSION = 'v1'
API_BASE = '/'  # API_BLUEPRINT prefix is 'api'

@api.representation('application/json')
def envelope_api(data, code, headers=None):
    """ API response envelope (for metadata/pagination).
    Optionally wraps JSON response in envelope.
    This is for successful requests only.

        data is the object returned by the API.
        code is the HTTP status code as an int
    """
    if not request.args.get('envelope'):
        return output_json(data, code, headers)
    message = 'success'
    if 'message' in data:
        message = data['message']
        del data['message']
    data = {
        'data': data,
        'code': code,
        'message': message
    }
    return output_json(data, code, headers)

@login_manager.request_loader
def load_user_from_request(request):
    # Only functional for API Endpoints
    if not request.endpoint or not request.endpoint.startswith("api."):
        return None

    # first, try to login using the api_key url arg
    api_key = request.args.get('api_key')
    if not api_key:
        return None
    user_id, _ = api_key.split('-')
    user = User.get_by_hashid(user_id)
    if user and user.check_api_key_hash(api_key):
        return user

def custom_abort(status_code, message, data=None):
    response = jsonify({
        'code': status_code,
        'data': data,
        'message': message,
    })
    response.status_code = status_code
    return response

def handle_api_error(err):
    return custom_abort(404, str(err))

class Resource(restful.Resource):
    method_decorators = []
    required_scopes = {}
    # applies to all inherited resources

    def __repr__(self):
        return "<Resource {0}>".format(self.__class__.__name__)

    def make_response(self, data, *args, **kwargs):
        return super().make_response(data, *args, **kwargs)


class BaseAPISchema():
    """ APISchema describes the input and output formats for
    resources. The parser deals with arguments to the API.
    The API responses are marshalled to json through get_fields
    """
    get_fields = {}

    def __init__(self):
        self.parser = reqparse.RequestParser()

    def parse_args(self):
        return self.parser.parse_args()

appname/controllers/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session, abort
from flask_login import login_user, logout_user, login_required, current_user

import appname.constants as constants

from appname.forms import SimpleForm
from appname.forms.login import LoginForm, SignupForm, RequestPasswordResetForm, ChangePasswordForm
from appname.models import db
from appname.models.user import User
from appname.models.teams import TeamMember
from appname.mailers.auth import ConfirmEmail, ResetPassword
from appname.extensions import login_manager, token, limiter

auth = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    login_hint = request.args.get('login_hint')
    return redirect(url_for('auth.login', login_hint=login_hint))

@auth.route("/login", methods=["GET", "POST"])
@limiter.limit("20/minute")
def login():
    if not constants.ALLOW_PASSWORD_LOGIN:
        return render_template("auth/oauth_only_login.html")

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for("main.home"))

    return render_template("auth/login.html", form=form)

@auth.route("/signup", methods=["GET", "POST"])
@limiter.limit("10/minute")
def signup():
    if not constants.ALLOW_SIGNUPS:
        return abort(404)

    form = SignupForm(invite_secret=request.args.get('invite_secret'))

    if form.validate_on_submit():
        team_secret = form.invite_secret.data
        invite = (TeamMember.query.filter_by(invite_secret=team_secret, activated=False)
                            .one_or_none())

        if invite:
            user = User(form.email.data, form.password.data,
                        email_confirmed=True, team=invite.team)
            invite.user = user
            db.session.add(invite)
        else:
            user = User(form.email.data, form.password.data)
        db.session.add(user)
        db.session.commit()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        if constants.REQUIRE_EMAIL_CONFIRMATION:
            # Send confirm email
            ConfirmEmail(user).send()

        flash("Welcome to appname.", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/signup.html", form=form, invite_secret=request.args.get('invite_secret'))

@auth.route("/auth/logout")
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("main.home"))

@auth.route("/confirm/<string:code>")
def confirm(code):
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)

    try:
        email = token.decode(code, salt=constants.EMAIL_CONFIRMATION_SALT)
    except Exception:
        email = None

    if not email:
        # TODO: Render a nice error page here.
        return abort(404)

    user = User.query.filter_by(email=email).first()
    if not user:
        return abort(404)
    user.email_confirmed = True
    db.session.commit()

    if current_user == user:
        flash('Succesfully confirmed your email', 'success')
        return redirect(url_for("dashboard_home.index"))
    else:
        flash('Confirmed your email. Please login to continue', 'success')
        return redirect(url_for("auth.login"))


@auth.route("/auth/resend-confirmation", methods=["GET", "POST"])
@limiter.limit("5/minute")
@login_required
def resend_confirmation():
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)
    if current_user.email_confirmed:
        return redirect(url_for("dashboard_home.index"))

    form = SimpleForm()
    if form.validate_on_submit():
        if ConfirmEmail(current_user).send():
            flash(
                "Sent confirmation to {}".format(
                    current_user.email),
                'success')
        return redirect(url_for("dashboard_home.index"))

    return render_template('auth/resend_confirmation.html', form=form)

@auth.route("/auth/reset_password", methods=["GET", "POST"])
@limiter.limit("20/hour")
def request_password_reset():
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))
    form = RequestPasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        if user:
            ResetPassword(user).send()
            flash("We sent you a password reset email.", "success")
            return redirect(url_for('auth.login'))
        else:
            flash("Hmm. That email doesn't appear to be registered ", "success")
    return render_template("auth/request_password_reset.html", form=form)

@auth.route("/auth/reset_password/<string:code>", methods=["GET", "POST"])
@limiter.limit("20/hour")
def reset_password(code):
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))

    try:
        email = token.decode(code, salt=constants.PASSWORD_RESET_SALT)
    except Exception:
        email = None

    if not email:
        return abort(403)

    form = ChangePasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=email).one()
        user.password = form.password.data
        db.session.commit()
        login_user(user)

        flash("Changed your password succesfully", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/reset_password.html", form=form)


@auth.route("/reauth", methods=["GET", "POST"])
def reauth():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        login_user(user)

        flash("Re-authenticated successfully.", "success")
        return redirect(request.args.get("next", url_for("user_settings.index")))
    return render_template("reauth.html", form=form)

@auth.route('/invite/<hashid:invite_id>/join')
@login_required
def join_team(invite_id):
    invite = TeamMember.query.get(invite_id)
    if not invite or invite.user != current_user:
        return abort(404)

    invite.activate(current_user.id)
    return redirect(url_for("dashboard_home.index"))

@auth.route('/join/<hashid:invite_id>/<string:secret>')
@limiter.limit("20/minute")
def invite_page(invite_id, secret):
    invite = TeamMember.query.get(invite_id)
    if not invite.invite_secret or invite.invite_secret != secret or invite.activated:
        return abort(404)

    if current_user.is_authenticated and invite.user == current_user:
        return redirect(url_for(".join_team", invite_id=invite.id))

    form = SignupForm(invite_secret=invite.invite_secret)
    return render_template("auth/invite.html", form=form, invite=invite)

appname/controllers/dashboard/__init__.py
from .home import blueprint as home_blueprint
from .team import blueprint as team_blueprint
from .files import blueprint as files_blueprint

dashboard_blueprints = [
    home_blueprint,
    team_blueprint,
    files_blueprint
]

appname/controllers/main.py
import stripe

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

from appname.extensions import cache

main = Blueprint('main', __name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_home.index'))
    return render_template('lander/index.html', stripe_publishable_key=stripe.publishable_key)

@main.route('/beta')
@cache.cached(timeout=1000, unless=lambda: current_user.is_authenticated)
def beta():
    return "Coming Soon", 200

appname/controllers/oauth/__init__.py
from .google import blueprint as google_blueprint

appname/controllers/realtime.py
from flask_login import current_user

from flask_socketio import join_room, leave_room, send
from appname.extensions import socketio

@socketio.on('connect')
def connect():
    if not current_user.is_authenticated:
        pass
    return

@socketio.on('disconnect')
def disconnect():
    if not current_user.is_authenticated:
        pass
    return

@socketio.on('join')
def on_join(data):
    username = data['username']
    room = data['room']
    join_room(room)
    send(username + ' has entered the room.', room=room)

@socketio.on('leave')
def on_leave(data):
    username = data['username']
    room = data['room']
    leave_room(room)
    send(username + ' has left the room.', room=room)

appname/controllers/store.py
import stripe

from flask import Blueprint, flash, render_template, request

from appname.models.user import User
from appname.extensions import csrf

from appname.mailers.store import PurchaseReceipt

store = Blueprint('store', __name__)

@store.route('/store')
def home():
    return render_template('store/product.html', stripe_publishable_key=stripe.publishable_key)


@store.route('/store/payment', methods=['POST'])
@csrf.exempt
def payment():

    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken']
    )

    stripe.Charge.create(
        customer=customer.id,
        amount=4999,
        currency='usd',
        description='Ingite Flask App Code'
    )

    user = User.lookup_or_create_by_email(request.form['stripeEmail'])
    PurchaseReceipt(user).send()

    flash("Payment processed. You'll get an email shortly", 'success')

    return render_template('store/product.html')

appname/helpers/__init__.py
# Helpers encompass logic that doesn't belong in controllers or
# in views. They are application specific and usually cannot be
# directly reused.

appname/models/teams/__init__.py
# To get Flask Migrate to pick these up, import this module in appname/manage.py
from .team_member import TeamMember  # noqa
from .team import Team  # noqa

appname/templates/tabler/401.html
{% extends "tabler/minimal_base.html" %}
{% block title %}appname error - 401{% endblock %}

{% block js %}

{% endblock %}

{% block body %}
<div class="page-content">
    <div class="container text-center">
        <div class="display-1 text-muted mb-5"><i class="si si-exclamation"></i> 401</div>
        <h1 class="h2 mb-3">Oops.. You just found an error page..</h1>
        <p class="h4 text-muted font-weight-normal mb-7">We are sorry but you are not authorized to access this page&hellip;</p>
        <a class="btn btn-primary" href="javascript:history.back()">
        <i class="fe fe-arrow-left mr-2"></i>Go back
        </a>
    </div>
</div>
{% endblock %}

appname/templates/tabler/_footer.html
<footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-auto ml-lg-auto">
                    <div class="row align-items-center">
                        <div class="col-auto">
                            <ul class="list-inline list-inline-dots mb-0">
                                <li class="list-inline-item">
                                    <a href="/">Home</a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="{{ url_for('user_settings.legal_compliance' )}}">Privacy</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
                    Copyright © 2019
                    <a href="{{ url_for('main.home' )}}">appname</a>. Powered by
                    <a href="https://github.com/sumukh/ignite" target="_blank">Ignite</a>
                    <!-- You must purchase a license of Ignite to remove the above disclaimer -->
                </div>
            </div>
        </div>
    </footer>

appname/templates/tabler/_header.html
<div class="header py-4">
    <div class="container">
        <div class="d-flex">
        <a class="header-brand" href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='public/ignite/ignite-logo@2x.png') }}" class="header-brand-img" alt="tabler logo">
        </a>
        <div class="d-flex order-lg-2 ml-auto">
            <div class="nav-item d-none d-md-flex">
                <a href="mailto://{{ constants.SUPPORT_EMAIL }}" class="btn btn-sm btn-outline-primary" target="_blank">Get help</a>
            </div>
            {% if current_user.is_authenticated %}
                <div class="dropdown">
                    <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                        <span class="avatar avatar-placeholder"></span>
                        <span class="ml-2 d-none d-lg-block">
                        {% if current_user.full_name %}
                            <span class="text-default">{{ current_user.full_name }}</span>
                            <small class="text-muted d-block mt-1">{{ current_user.email }}</small>
                        {% else %}
                            <span class="text-default">{{ current_user.email }}</span>
                        {% endif %}
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        {% for membership in current_user.memberships %}
                            <a href="{{ url_for('dashboard_home.home', team_id=membership.team.id) }}" class="dropdown-item">
                                <i class="dropdown-icon fe fe-log-in"></i>  {{ membership.team.name }} Dashboard
                            </a>
                            <div class="dropdown-divider"></div>
                        {% endfor %}
                        <a class="dropdown-item" href="{{ url_for('user_settings.account') }}">
                            <i class="dropdown-icon fe fe-settings"></i> Account Settings
                        </a>

                        <a class="dropdown-item" href="mailto://{{ constants.SUPPORT_EMAIL }}">
                            <i class="dropdown-icon fe fe-help-circle"></i> Need help?
                        </a>
                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                            <i class="dropdown-icon fe fe-log-out"></i> Sign out
                        </a>
                    </div>
                </div>
            {% else %}
            <div class="nav-item d-none d-md-flex">
                <a class="btn btn-sm btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>
            </div>
            {% endif %}
        </div>
        <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
            <span class="header-toggler-icon"></span>
        </a>
        </div>
    </div>
</div>

appname/templates/tabler/_navbar.html
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 ml-auto">
                <form class="input-icon my-3 my-lg-0">
                    <input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
                    <div class="input-icon-addon">
                        <i class="fe fe-search"></i>
                    </div>
                </form>
            </div>
            <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item {{ 'active' if request.blueprint == 'dashboard_home' }}">
                        <a href="{{ url_for('dashboard_home.index') }}" class="nav-link {{ 'active' if request.endpoint == 'dashboard_home.index' }}">
                            <i class="fe fe-home"></i> Home
                        </a>
                    </li>
                    {% if team %}
                    <li class="nav-item {{ 'active' if request.blueprint == 'dashboard_team' }}">
                        <a href="{{ url_for('dashboard_team.index', team_id=team.id) }}" class="nav-link  {{ 'active' if request.endpoint == 'dashboard_team.index' }}">
                            <i class="fe fe-users"></i> Your Team
                        </a>
                    </li>
                    <li class="nav-item {{ 'active' if request.blueprint == 'dashboard_files' }}">
                        <a href="{{ url_for('dashboard_files.index', team_id=team.id) }}" class="nav-link  {{ 'active' if request.endpoint == 'dashboard_files.index' }}">
                            <i class="fe fe-file"></i> Shared Files
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown">
                            <i class="fe fe-box"></i> Dropdown</a>
                        <div class="dropdown-menu dropdown-menu-arrow">
                            <a href="#" class="dropdown-item">Menu Item 1</a>
                            <a href="#" class="dropdown-item ">Menu Item 2</a>
                            <a href="#" class="dropdown-item ">Menu Item 3</a>
                        </div>
                    </li>

                    {% endif %}
                    <li class="nav-item {{ 'active' if request.endpoint.startswith('user_settings') }}">
                        <a href="{{ url_for('user_settings.index') }}" class="nav-link  {{ 'active' if request.endpoint.startswith('user_settings') }}">
                            <i class="fe fe-settings"></i> User Settings
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item {{ 'active' if request.endpoint == 'main.home' }}">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{{ render_flashes() }}

appname/templates/tabler/dashboard_base.html
{% from "helpers/_flashes.html" import render_flashes %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "tabler_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='public/ignite/ignite-icon.png') }}">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='public/ignite/ignite-icon.png') }}">

        {% block css %}
        {% endblock %}
        {% assets "tabler_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block head_js %}
            <!-- Pageblocking scripts should go here. Other scripts should go in the `js` block. -->
        {% endblock %}
    </head>

    <body>
        <div class="page">
            <div class="page-main">
                {% include 'tabler/_header.html' with context %}
                {% include 'tabler/_navbar.html' with context %}

                {% block body %}
                {% endblock %}

            </div>
            {% include 'tabler/_footer.html' with context %}
        </div>
    </body>



    {% block js %}
    {% endblock %}

</html>

appname/templates/tabler/minimal_base.html
{% from "helpers/_flashes.html" import render_flashes %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "tabler_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='public/ignite/ignite-icon.png') }}">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='public/ignite/ignite-icon.png') }}">
        {% block css %}
        {% endblock %}

        {% block head_js %}
            <!-- Pageblocking scripts should go here. Other scripts should go in the `js` block. -->
        {% endblock %}
    </head>

    <body>
        <div class="page">
            {% block body %}
            {% endblock %}
        </div>
    </body>
    {% assets "tabler_js" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block js %}
    {% endblock %}
</html>