appname/__init__.py
#! ../env/bin/python

from flask import Flask, render_template, request, g
from webassets.loaders import PythonLoader as PythonAssetsLoader

from appname import assets
from appname import constants
from appname.models import db
from appname.api.resources import api_blueprint
from appname.api import handle_api_error
from appname.controllers.main import main
from appname.controllers.auth import auth
from appname.controllers.oauth import google_blueprint
from appname.controllers.store import store
from appname.controllers.settings import settings_blueprint
from appname.controllers.admin.jobs import jobs
from appname.controllers.webhooks.stripe import stripe_blueprint
from appname.controllers.dashboard import dashboard_blueprints

from appname import utils
from appname.helpers import view as view_helpers
from appname.converter import custom_converters
from appname.extensions import (
    admin,
    assets_env,
    cache,
    csrf,
    debug_toolbar,
    hashids,
    login_manager,
    limiter,
    mail,
    rq2,
    sentry,
    storage,
    stripe,
    token
)
from appname.forms import SimpleForm


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. appname.settings.ProdConfig
    """

    app = Flask(__name__)
    app.config.from_object(object_name)

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # initalize Flask Login
    login_manager.init_app(app)

    # initialize Flask-RQ2 (job queue)
    rq2.init_app(app)

    # CSRF Protection
    csrf.init_app(app)

    # File Storage
    storage.init_app(app)

    # Special URL converters
    custom_converters.init_app(app)

    token.init_app(app)
    mail.init_app(app)
    limiter.init_app(app)
    stripe.init_app(app)
    hashids.init_app(app)

    if app.config.get('SENTRY_DSN') and not app.debug:
        sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        @app.errorhandler(500)
        def internal_server_error(error):
            return render_template('errors/500.html',
                                   event_id=g.sentry_event_id,
                                   public_dsn=sentry.client.get_public_dsn(
                                       'https')
                                   ), 500

    @app.errorhandler(404)
    def not_found_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('errors/404.html'), 404

    @app.errorhandler(401)
    def permission_denied_error(error):
        if request.path.startswith("/api"):
            return handle_api_error(error)
        return render_template('tabler/401.html'), 401

    @app.before_request
    def check_for_confirmation(*args, **kwargs):
        pass
        # TODO: Check later.
        # if REQUIRE_EMAIL_CONFIRMATION:
        #     # If we have a logged in user, we can check if they have confirmed their email or not.
        #     if not current_user.is_authenticated or current_user.email_confirmed:
        #         return
        #     resend_confirm_link = url_for('auth.resend_confirmation')
        #     text = Markup(
        #         'Please confirm your email. '
        #         '<a href="{}" class="alert-link">Click here to resend</a>'.format(resend_confirm_link))
        #     flash(text, 'warning')

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # Set some globals for Jinja templating
    app.jinja_env.globals.update({
        'utils': utils,
        'view_helpers': view_helpers,
        'debug': app.debug,
        'constants': constants,
        'simple_form': SimpleForm,
        'features': {
            'oauth':  app.config["GOOGLE_OAUTH_CLIENT_ID"] != 'bad_key',
            'segment':  app.config["SEGMENT_ANALYTICS_KEY"],
        },
    })

    # register our blueprints
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(google_blueprint, url_prefix='/oauth')
    app.register_blueprint(store)
    app.register_blueprint(settings_blueprint)

    # Register user dashboard blueprints
    for blueprint in dashboard_blueprints:
        app.register_blueprint(blueprint, url_prefix='/dashboard')

    # API
    app.register_blueprint(api_blueprint, url_prefix='/api')
    csrf.exempt(api_blueprint)

    app.register_blueprint(stripe_blueprint, url_prefix='/webhooks')
    csrf.exempt(stripe_blueprint)

    # Admin Tools
    app.register_blueprint(jobs, url_prefix='/admin/rq')
    admin.init_app(app)

    # If you use websockets/realtime features
    # socketio.init_app(app)

    return app

appname/controllers/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session, abort
from flask_login import login_user, logout_user, login_required, current_user

import appname.constants as constants

from appname.forms import SimpleForm
from appname.forms.login import LoginForm, SignupForm, RequestPasswordResetForm, ChangePasswordForm
from appname.models import db
from appname.models.user import User
from appname.models.teams import TeamMember
from appname.mailers.auth import ConfirmEmail, ResetPassword
from appname.extensions import login_manager, token, limiter

auth = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    login_hint = request.args.get('login_hint')
    return redirect(url_for('auth.login', login_hint=login_hint))

@auth.route("/login", methods=["GET", "POST"])
@limiter.limit("20/minute")
def login():
    if not constants.ALLOW_PASSWORD_LOGIN:
        return render_template("auth/oauth_only_login.html")

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for("main.home"))

    return render_template("auth/login.html", form=form)

@auth.route("/signup", methods=["GET", "POST"])
@limiter.limit("10/minute")
def signup():
    if not constants.ALLOW_SIGNUPS:
        return abort(404)

    form = SignupForm(invite_secret=request.args.get('invite_secret'))

    if form.validate_on_submit():
        team_secret = form.invite_secret.data
        invite = (TeamMember.query.filter_by(invite_secret=team_secret, activated=False)
                            .one_or_none())

        if invite:
            user = User(form.email.data, form.password.data,
                        email_confirmed=True, team=invite.team)
            invite.user = user
            db.session.add(invite)
        else:
            user = User(form.email.data, form.password.data)
        db.session.add(user)
        db.session.commit()
        session['current_team_membership_id'] = user.primary_membership_id
        login_user(user)

        if constants.REQUIRE_EMAIL_CONFIRMATION:
            # Send confirm email
            ConfirmEmail(user).send()

        flash("Welcome to appname.", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/signup.html", form=form, invite_secret=request.args.get('invite_secret'))

@auth.route("/auth/logout")
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("main.home"))

@auth.route("/confirm/<string:code>")
def confirm(code):
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)

    try:
        email = token.decode(code, salt=constants.EMAIL_CONFIRMATION_SALT)
    except Exception:
        email = None

    if not email:
        # TODO: Render a nice error page here.
        return abort(404)

    user = User.query.filter_by(email=email).first()
    if not user:
        return abort(404)
    user.email_confirmed = True
    db.session.commit()

    if current_user == user:
        flash('Succesfully confirmed your email', 'success')
        return redirect(url_for("dashboard_home.index"))
    else:
        flash('Confirmed your email. Please login to continue', 'success')
        return redirect(url_for("auth.login"))


@auth.route("/auth/resend-confirmation", methods=["GET", "POST"])
@limiter.limit("5/minute")
@login_required
def resend_confirmation():
    if not constants.REQUIRE_EMAIL_CONFIRMATION:
        abort(404)
    if current_user.email_confirmed:
        return redirect(url_for("dashboard_home.index"))

    form = SimpleForm()
    if form.validate_on_submit():
        if ConfirmEmail(current_user).send():
            flash(
                "Sent confirmation to {}".format(
                    current_user.email),
                'success')
        return redirect(url_for("dashboard_home.index"))

    return render_template('auth/resend_confirmation.html', form=form)

@auth.route("/auth/reset_password", methods=["GET", "POST"])
@limiter.limit("20/hour")
def request_password_reset():
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))
    form = RequestPasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        if user:
            ResetPassword(user).send()
            flash("We sent you a password reset email.", "success")
            return redirect(url_for('auth.login'))
        else:
            flash("Hmm. That email doesn't appear to be registered ", "success")
    return render_template("auth/request_password_reset.html", form=form)

@auth.route("/auth/reset_password/<string:code>", methods=["GET", "POST"])
@limiter.limit("20/hour")
def reset_password(code):
    if not current_user.is_anonymous:
        flash('You must be logged out to reset your password', 'warning')
        return redirect(url_for("dashboard_home.index"))

    try:
        email = token.decode(code, salt=constants.PASSWORD_RESET_SALT)
    except Exception:
        email = None

    if not email:
        return abort(403)

    form = ChangePasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=email).one()
        user.password = form.password.data
        db.session.commit()
        login_user(user)

        flash("Changed your password succesfully", "success")
        return redirect(request.args.get("next") or url_for("dashboard_home.index"))

    return render_template("auth/reset_password.html", form=form)


@auth.route("/reauth", methods=["GET", "POST"])
def reauth():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        login_user(user)

        flash("Re-authenticated successfully.", "success")
        return redirect(request.args.get("next", url_for("user_settings.index")))
    return render_template("reauth.html", form=form)

@auth.route('/invite/<hashid:invite_id>/join')
@login_required
def join_team(invite_id):
    invite = TeamMember.query.get(invite_id)
    if not invite or invite.user != current_user:
        return abort(404)

    invite.activate(current_user.id)
    return redirect(url_for("dashboard_home.index"))

@auth.route('/join/<hashid:invite_id>/<string:secret>')
@limiter.limit("20/minute")
def invite_page(invite_id, secret):
    invite = TeamMember.query.get(invite_id)
    if not invite.invite_secret or invite.invite_secret != secret or invite.activated:
        return abort(404)

    if current_user.is_authenticated and invite.user == current_user:
        return redirect(url_for(".join_team", invite_id=invite.id))

    form = SignupForm(invite_secret=invite.invite_secret)
    return render_template("auth/invite.html", form=form, invite=invite)

appname/controllers/dashboard/__init__.py
from .home import blueprint as home_blueprint
from .team import blueprint as team_blueprint
from .files import blueprint as files_blueprint

dashboard_blueprints = [
    home_blueprint,
    team_blueprint,
    files_blueprint
]

appname/controllers/main.py
import stripe

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

from appname.extensions import cache

main = Blueprint('main', __name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_home.index'))
    return render_template('lander/index.html', stripe_publishable_key=stripe.publishable_key)

@main.route('/beta')
@cache.cached(timeout=1000, unless=lambda: current_user.is_authenticated)
def beta():
    return "Coming Soon", 200

appname/controllers/oauth/__init__.py
from .google import blueprint as google_blueprint

appname/controllers/settings.py
from flask import Blueprint, render_template, flash, redirect, url_for, Response, request
from flask_login import login_required, current_user


from appname.constants import SUPPORT_EMAIL
from appname.extensions import stripe
from appname.models import db
from appname.forms import SimpleForm
from appname.forms.login import ChangePasswordForm
from appname.forms.account import ChangeProfileForm
from appname.helpers.gdpr import GDPRExport
from appname.utils.token import generate_api_secret
from appname.billing_plans import plans_by_name

from appname.extensions import stripe

settings_blueprint = Blueprint('user_settings', __name__)

@settings_blueprint.route('/settings')
@login_required
def index():
    return redirect(url_for("user_settings.account"))

@settings_blueprint.route('/settings/account', methods=['GET', 'POST'])
@login_required
def account():
    form = ChangeProfileForm()
    if form.validate_on_submit():
        current_user.full_name = form.name.data
        db.session.add(current_user)
        db.session.commit()


    return render_template('/settings/account.html', form=form)

@settings_blueprint.route('/settings/password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        db.session.commit()
        flash("Changed password", "success")
    else:
        form = ChangePasswordForm()
        return render_template('/settings/change_password.html', form=form)

@settings_blueprint.route('/settings/legal')
@login_required
def legal_compliance():
    form = SimpleForm()

    return render_template('/settings/legal_compliance.html', form=form)

@settings_blueprint.route('/settings/oauth')
@login_required
def oauth():
    return render_template('/settings/oauth.html')

@settings_blueprint.route('/settings/billing')
@login_required
def billing():
    form = SimpleForm()
    if request.args.get('success'):
        flash('Processing your payment. You may need to refresh the page.', 'success')
    return render_template('/settings/billing.html.jinja2', plans=plans_by_name,
                           stripe_publishable_key=stripe.publishable_key, form=form)


@settings_blueprint.route('/settings/api', methods=['GET', 'POST'])
@login_required
def api():
    form = SimpleForm()
    if form.validate_on_submit():
        api_key = generate_api_secret(current_user)
        current_user.hash_api_key(api_key)

        flash("Your API Key is: '{}'. It will not be displayed again, so make sure you save it.".format(api_key),
              'success')
    return render_template('/settings/api.html', form=form)

@settings_blueprint.route('/settings/memberships')
@login_required
def memberships():
    form = SimpleForm()
    memberships = current_user.memberships
    return render_template('/settings/memberships.html', form=form, memberships=memberships)

@settings_blueprint.route('/settings/legal/pii_download', methods=['POST'])
@login_required
def pii_download():
    form = SimpleForm()

    if form.validate_on_submit():
        return Response(GDPRExport(current_user, current_user).export_user_pii_json(),
                        mimetype='application/json',
                        headers={'Content-Disposition': 'attachment;filename=user-export.json'})
    else:
        flash('Please try submitting the form again', 'warning')

    return redirect(url_for("user_settings.legal_compliance"))

@settings_blueprint.route('/settings/legal/pii_send_export', methods=['POST'])
@login_required
def pii_notification():
    # Should be queued as a job
    form = SimpleForm()
    if form.validate_on_submit():
        GDPRExport(current_user, current_user).send_pii_export()
        flash("Export queued & will be sent to your email", 'success')
    else:
        flash('Please try submitting the form again', 'warning')
    return redirect(url_for("user_settings.legal_compliance"))

@settings_blueprint.route('/settings/legal/account_deletion', methods=['POST'])
@login_required
def account_deletion():
    form = SimpleForm()
    if form.validate_on_submit():
        # TODO: Actual deletion scheduling
        flash("Please email {0} to delete your account".format(SUPPORT_EMAIL), 'warning')
    else:
        flash('Please try submitting the form again', 'warning')
    return redirect(url_for("user_settings.legal_compliance"))

appname/helpers/__init__.py
# Helpers encompass logic that doesn't belong in controllers or
# in views. They are application specific and usually cannot be
# directly reused.

appname/templates/settings/api.html
{% extends "tabler/dashboard_base.html" %}
{% from "helpers/_formhelpers.html" import render_field %}

{% block title %}appname settings (API) {% endblock %}

{% block body %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="row">
            <div class="col-3">
                {% include 'settings/sidebar.html' %}
            </div>
            <div class="col-9">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">API</h3>
                    </div>
                    <div class="card-body">
                        <p> The API allows you to access certain functionality programatically. It grants control of your account. </p>
                    {% if current_user.user_api_key_hash %}
                        <p> You account already has an API Key, but it is hidden for security. You can regenerate your key by clicking on 'Generate New API Key'</p>
                    {% endif %}
                    </div>
                    <form role="form" action="{{ url_for('user_settings.api') }}" method="post">
                            {{ form.hidden_tag() }}
                        <div class="card-footer text-left">
                            <div class="d-flex">
                                <button type="submit" class="btn btn-primary">Generate New API Key</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

appname/templates/settings/billing.html.jinja2
{% extends "tabler/dashboard_base.html" %} {% from "helpers/_formhelpers.html" import render_field %} {% block title %}appname settings{% endblock %} {% block body %} {% if stripe_publishable_key %}
<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe('{{ stripe_publishable_key }}');

    function purchase(planId, teamId) {
        stripe.redirectToCheckout({
            lineItems: [
                // Replace with the ID of your price
                {
                    price: planId,
                    quantity: 1
                }
            ],
            clientReferenceId: teamId,
            mode: 'subscription',
            successUrl: "{{ url_for('user_settings.billing', success=1, _external=True) }}",
            cancelUrl: "{{ url_for('user_settings.billing', cancel=1, _external=True) }}",
            customerEmail: '{{ current_user.email }}',
        }).then(function(result) {
            // If `redirectToCheckout` fails due to a browser or network
            // error, display the localized error message to your customer
            // using `result.error.message`.
            alert(result.error.message);
        });
    }
</script>
{% endif %}


<div class="my-3 my-md-5">
    <div class="container">
        <div class="row">
            <div class="col-3">
                {% include 'settings/sidebar.html' %}
            </div>
            <div class="col-9">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Upgrade</h3>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                                <thead>
                                    <tr>
                                        <th>Team</th>
                                        <th class="text-center">Plan</th>
                                        <th class="text-center">Manage</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for member in current_user.active_memberships %}
                                    <tr>
                                        <td>
                                            <div>{{ member.team.name }}</div>
                                        </td>
                                        <td class="text-center">
                                            {{ member.team.billing_plan.friendly_name }}
                                        </td>
                                        <td class="text-center">
                                            {% if not member.team.is_paid_plan %}
                                            <a class="btn btn-primary text-white" onclick="purchase('{{ plans["monthly_premium"].stripe_product_id }}', '{{ member.team.id}}')">
                                                    Upgrade ($10/month)
                                            </a>
                                            <a class="btn btn-primary text-white " onclick="purchase('{{ plans["annual_premium"].stripe_product_id }}', '{{ member.team.id}}')">
                                                    Save 20% ($100/year)
                                            </a>
                                            {% endif %}

                                            {% if member.team.billing_customer_id %}
                                            <form role="form" action="{{ url_for('dashboard_team.billing_portal', team_id=member.team.id) }}" method="post">
                                                {{ form.hidden_tag() }}
                                                <button type="submit" class="btn btn-secondary">Manage Subscription & Payments</button>
                                            </form>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

appname/templates/settings/legal_compliance.html
{% extends "tabler/dashboard_base.html" %}
{% from "helpers/_formhelpers.html" import render_field %}

{% block title %}appname settings{% endblock %}

{% block body %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="row">
            <div class="col-3">
                {% include 'settings/sidebar.html' %}
            </div>
            <div class="col-9">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Legal Compliance</h3>
                    </div>
                    <div class="card-body">
                        Here's a copy of our standard terms & privacy policies. Questions about our policies, as well info about
                        our GDPR policies can be directed over email to {{ constants.SUPPORT_EMAIL }}
                    </div>
                    <div class="card-footer">
                        <div class="btn-list text-center">
                            <a href="#" class="btn btn-secondary">Privacy Policy</a>
                            <a href="#" class="btn btn-secondary">Terms and Conditions</a>
                            <a href="#" class="btn btn-secondary">Data Processing Amendment</a>
                        </div>

                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">User Data Export</h3>
                    </div>
                    <div class="card-body">
                        appname provides a way for users to export their personal data. The fields below will provide
                        a way to access the data.
                    </div>
                    <div class="card-footer">
                        <div class="container">
                            <div class="row">
                                  <div class="col">
                                        <form role="form" action="{{ url_for('user_settings.pii_download') }}" method="post">
                                            {{ form.hidden_tag() }}
                                            <button type="submit" class="btn btn-primary btn-block"><i class="fe fe-file"></i> Download Data Export</button>
                                        </form>
                                    </div>

                                  <div class="col">
                                    <form role="form" action="{{ url_for('user_settings.pii_notification') }}" method="post">
                                        {{ form.hidden_tag() }}
                                        <button type="submit" class="btn btn-primary btn-block"><i class="fe fe-mail"></i>Send Data Export</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Data Deletion</h3>
                    </div>
                    <div class="card-body">
                        appname provides a way for users to delete their personal data. Teams will only be deleted when you are the only member
                        of the team.
                    </div>
                    <div class="card-footer">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <form role="form" action="{{ url_for('user_settings.account_deletion') }}" method="post">
                                        {{ form.hidden_tag() }}
                                        <button type="submit" class="btn btn-danger"><i class="fe fe-trash"></i> Delete Account</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

appname/templates/settings/sidebar.html
<h3 class="page-title mb-5">Settings</h3>
<div>
    <div class="list-group list-group-transparent mb-0">
        <a href="{{ url_for('user_settings.account') }}"
            class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.account' }}">
            <span class="icon mr-3"><i class="fe fe-user"></i></span>Account Settings
        </a>
        <a href="{{ url_for('user_settings.change_password') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.change_password' }}">
            <span class="icon mr-3"><i class="fe fe-lock"></i></span>Change Password
        </a>
        <a href="{{ url_for('user_settings.oauth') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.oauth' }}">
            <span class="icon mr-3"><i class="fa fa-google"></i></span>Linked Accounts
        </a>

        <div class="dropdown-divider"></div>
        <a href="{{ url_for('user_settings.billing') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.billing' }}">
            <span class="icon mr-3"><i class="fe fe-credit-card"></i></span>Billing
        </a>


        <a href="{{ url_for('user_settings.memberships') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.memberships' }}">
            <span class="icon mr-3"><i class="fe fe-users"></i></span>Team Memberships
        </a>

        <a href="{{ url_for('user_settings.api') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.api' }}">
            <span class="icon mr-3"><i class="fe fe-zap"></i></span>API Access
        </a>


        <div class="dropdown-divider"></div>
        <a href="{{ url_for('user_settings.legal_compliance') }}"
        class="list-group-item list-group-item-action d-flex align-items-center  {{ 'active' if request.endpoint == 'user_settings.legal_compliance' }}">
            <span class="icon mr-3"><i class="fe fe-shield"></i></span>Legal & Compliance
        </a>
    </div>
    <div class="mt-6">
        <a href="mailto://{{ constants.SUPPORT_EMAIL }}" class="btn btn-secondary btn-block">
            <span class="icon mr-3"><i class="fe fe-message-square"></i></span>
            Get help
        </a>
    </div>
</div>